name: Build

on:
  push:
    branches:
      - 'master'
      - 'main'
    tags:
      - 'v*'

  schedule:
    - cron: '55 5 * * 5'

jobs:
  build:
    name: Build
    uses: s4u/.github/.github/workflows/maven-build.yml@master

    secrets:
      SIGN_KEY:       ${{ secrets.SIGN_KEY }}
      SIGN_KEY_PASS:  ${{ secrets.SIGN_KEY_PASS }}
      OSS_USER:       ${{ secrets.OSS_USER }}
      OSS_PASS:       ${{ secrets.OSS_PASS }}
      TECH_TOKEN:     ${{ secrets.TECH_TOKEN }}
      GITHUB_TOKEN:   ${{ secrets.GITHUB_TOKEN }}

